<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<div class="container">
    <div class="checkout-success">
        <p><?= $block->escapeHtml(__('Your Order Failed Please Try Again Later.')) ?></p>

        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?= $block->escapeUrl($block->getBaseUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
            </div>
        </div>
    </div>
</div>
